### ISSUE TITLE
Teams and tags are not supported when deploying using CRDs

### ISSUE THREAD

**Issue by mortenlj** [fiaas/fiaas-deploy-daemon#29]
In the kafka deploy method used at FINN, we support setting teams and tags labels on the deployed objects. This is used to track metrics and ownership across deployments.

When deploying using CRDs, we have not implemented support for these labels, and instead hardcode them to empty lists.

For FINN to move to CRD deployments, this needs to be supported. For us to get to python3 (#6) we need to get rid of the kafka code, which can only happen when FINN has completed the move to CRDs.

**Comment by oyvindio** [comment]
The requirement in this issue is to make the existing teams and tags mechanism in the pipeline consumer possible to configure via the Application CRD.
There is a somewhat similar requirement that is currently solved in mast: In mast there is some code that allows the orchestrating system (typically Spinnaker) to set some annotations that is injected into the `annotations` key in the FIAAS config that is used in the Application resource. Currently these are used to add traceability metadata like links to the commit and CI build that triggered the deploy.

At the risk of increasing the scope here, maybe this could be generalized to a mechanism to set some global metadata (labels and/or annotations) that is applied to all resources fiaas generates, which could solve both these requirements? This will move the responsibility of setting the teams and tags labels properly from fiaas-deploy-daemon to the orchestrating system, or the system that sits in between and creates the Application resources. This will mean that the team and tags labels will not necessarily look the same (or even exist) everywhere FIAAS is used.

**Comment by mortenlj** [comment]
The Spinnaker <-> Mast thing uses annotations, but I guess we could handle annotations and labels in the same way. Would the natural thing be to add two new keys to `spec` then?

How should we model this? Do we need to be able to specify labels and annotations per object (like in `fiaas.yml`), or should we just have one set of annotations/lables that gets applied to everything?

A while back someone (I forget who) talked about wanting to be able to configure labels/annotations to apply per namespace (in `cluster_config.yml`). Would it be natural to tackle that feature while we are at it?

**Comment by oyvindio** [comment]
Another use case for annotations that are propagated to all resources fiaas manages could be: Set a callback URL on the application resource which is propagated to the applicationstatus, which can  be used later by some other tool to report status for the deployment back to the initiating system.  Much like what `pipeline.Reporter` currently does, but enabling keeping the implementation outside of fiaas-deploy-daemon.

**Comment by oyvindio** [comment]
> The Spinnaker <-> Mast thing uses annotations, but I guess we could handle annotations and labels in the same way. Would the natural thing be to add two new keys to `spec` then?

I think this might be the most sensible way of expressing it. 
Some other options I guess could be:
- using an annotation on the application resource to store the labels and annotations 
- copying (some?) annotations and labels from the application resource's metadata itself

But I think these both seem a bit cumbersome.

> How should we model this? Do we need to be able to specify labels and annotations per object (like in `fiaas.yml`), or should we just have one set of annotations/lables that gets applied to everything?

I don't really have a strong opinion either way, but I think having the ability to set labels and annotations that will be propagated to all resources managed by fiaas will solve the use cases that are covered in this issue currently. If we (initially?) only want to support a set of labels and/or annotations for everything we should probably try to model it in a way that is extendable to support labels/annotations per resource too.

**Comment by xavileon** [comment]
> A while back someone (I forget who) talked about wanting to be able to configure labels/annotations to apply per namespace (in cluster_config.yml). Would it be natural to tackle that feature while we are at it?

@mortenlj @oyvindio that was me :) We have some requirements from different sites to set up per-namespace annotations/labels to different objects (but not necessarily to all of them), much like we do in `paas.yml` file (pre-mast processing) but at the namespace level (in the `cluster_config.yml`). One use case we have is to apply the same whitelisting IP list too all ingresses in a namespace, so changing that list would be transparent to the users. That seems out of scope for mast (only orchestration layer) and it may seem more related to a cluster config in FIAAS. I understand the use cases are slightly different though, and it highly depends on the mapping of namespaces to teams you may have?

**Comment by mortenlj** [comment]
I have thought a bit more about it, and think that handling the annotations/labels per namespace in this issue is a bad idea. The reason is that the way we load the configuration doesn't really lend itself to loading the complex object needed to describe annotations or labels. It makes more sense to tackle #12 first, then do annotations/labels per namespace.

For CRDs I suggest we add two new keys to `spec`:
- `additional_annotations`
- `additional_labels`

Each will have support for these sub-keys:
- `global`: Applied to all objects created by fdd
- `ingress`: Applied to ingress
- `service`: Applied to service
- `deployment`: Applied to deployment
- `horizontalpodautoscaler`: Applied to HPA
- `pod`: Applied to all pods

Then Mast or Skipshund can set the labels or annotations it wants, and get them propagated to the relevant objects.

**Comment by oyvindio** [comment]
> For CRDs I suggest we add two new keys to `spec`:
> 
>     * `additional_annotations`
> 
>     * `additional_labels`
> 

I think this looks like a good way of modeling this. Any reason why the spec level keys shouldn't just be `annotations` and `labels`?


> Each will have support for these sub-keys:

I think applicationstatus or status should also be in this list

**Comment by mortenlj** [comment]
> Any reason why the spec level keys shouldn't just be `annotations` and `labels`?

Mostly to differentiate between these and the ones that appear under `config`.

> I think applicationstatus or status should also be in this list

Makes sense. It also probably doesn't make sense to support those objects in `fiaas.yml`, right?

**Comment by oyvindio** [comment]
> Mostly to differentiate between these and the ones that appear under `config`.

Okay, it makes it a bit harder to do the wrong thing then.

> Makes sense. It also probably doesn't make sense to support those objects in `fiaas.yml`, right?

No, I don't think it is necessary to support it in fiaas.yml. I don't think applications should care about the status object at all

Since we are adding another way to configure annotations and labels that end up on the resources fiaas manages, we will also have to think about precedence. I think it makes sense that the order of precedence is:
1. labels managed by fiaas itself, such as `app`, or `fiaas/*`
2. additional_labels, additional_annotations
3. annotations and labels from fiaas.yml

I.e. `app` and `fiaas/*` labels/annotations managed by FIAAS internally can never be overridden. Also, additional_labels and additional_annotations take precedence over labels and annotations from fiaas.yml.
