### ISSUE TITLE
Reduce memory requested for datadog sidecar

### ISSUE THREAD

**Issue by gregjones** [fiaas/fiaas-deploy-daemon#75]
At the moment, the datadog integration requests 2GB of RAM for the pod. From metrics in the cluster, we can see that the max that's being used is around 220MB, so we'd like to reduce this, as the saving over all the pods being run will be quite large.

Either we can reduce the hardcoded value, maybe initially to 1GB, and then later to 500MB. Or, we could introduce deploy-daemon configuration for this. Any preference?

**Comment by mortenlj** [comment]
I would rather just reduce the hardcoded value than introduce yet another config parameter, but it's not terribly important.

On the other hand, we have discussed the high memory usage for the datadog sidecar before (probably in the Schibsted Slack somewhere), and the reason for the high value was because datadog became unstable and started to do strange things with the metrics when it didn't have lots of memory available.

This might be better in later versions of datadog, so if you want to experiment with it, all the better. 😄

**Comment by oyvindio** [comment]
I don't really have a strong opinion on this; if it makes it easier to tune the resource values to something that works well, I think it is fine to add a CLI flag (or flags) for this.
