### ISSUE TITLE
Delete ApplicationStatus resources when deleting Application

### ISSUE THREAD

**Issue by oyvindio** [fiaas/fiaas-deploy-daemon#78]
When deleting an Application resource, all managed resources are deleted, except for the ApplicationStatus resources created on deployment. I think it makes sense to also delete the ApplicationStatus resources, since deleting an application typically means that it is decommisioned

**Comment by mortenlj** [comment]
We have briefly discussed using `ownerReference` on objects created as a result of an `Application` object, which would make Kubernetes delete the dependent objects when we delete the `Application` (I think that's what it says here: https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/).

Maybe a first step would be to make sure to set `ownerReference` on all objects created by FDD, linking them to the `Application` that triggered their creation?

We might still want to explicitly delete matching `ApplicationStatus` objects, because right now none of them have `ownerReference` set anyway.

**Comment by oyvindio** [comment]
That is a good point about ownerReference, that might be a part of the solution for this. Maybe we could use it to replace the "delete resource" codepath in fiaas-deploy-daemon too.
